include:
  - project: 'uji-cirtesu-irslab/urobf/urf-environment'
    ref: master
    file: '/ci/cpp-template.yml'

variables:
  PACKAGE_NAME: "urf_common_cpp"

build_static_debug_linux:
  extends: .conan_build_job_linux
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "False"

build_static_release_linux:
  extends: .conan_build_job_linux
  needs:
    - job: build_static_debug_linux
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "False"

build_shared_release_linux:
  extends: .conan_build_job_linux
  needs:
    - job: build_static_debug_linux
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "True"

build_shared_debug_linux:
  extends: .conan_build_job_linux
  needs:
    - job: build_static_debug_linux
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "True"
    
deploy_shared_release_linux:
  extends: .conan_upload_job_linux
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "True"

deploy_shared_debug_linux:
  extends: .conan_upload_job_linux
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "True"

deploy_static_release_linux:
  extends: .conan_upload_job_linux
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "False"

deploy_static_debug_linux:
  extends: .conan_upload_job_linux
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "False"

build_static_debug_windows:
  extends: .conan_build_job_windows
  needs:
    - job: build_shared_debug_linux
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "False"

build_static_release_windows:
  extends: .conan_build_job_windows
  needs:
    - job: build_static_debug_windows
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "False"

build_shared_release_windows:
  extends: .conan_build_job_windows
  needs:
    - job: build_static_debug_windows
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "True"

build_shared_debug_windows:
  extends: .conan_build_job_windows
  needs:
    - job: build_static_debug_windows
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "True"
    
deploy_shared_release_windows:
  extends: .conan_upload_job_windows
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "True"

deploy_shared_debug_windows:
  extends: .conan_upload_job_windows
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "True"

deploy_static_release_windows:
  extends: .conan_upload_job_windows
  variables:
    BUILD_TYPE: "Release"
    BUILD_SHARED: "False"

deploy_static_debug_windows:
  extends: .conan_upload_job_windows
  variables:
    BUILD_TYPE: "Debug"
    BUILD_SHARED: "False"
