stages:
  - prepare
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

install:
  stage: prepare
  tags:
    - urf
    - linux
  script:
    - conan install . -if build/conan
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/

build:
  stage: build  
  tags:
    - urf
    - linux
  script:
    - conan build . -if build/conan
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/
    
deploy:
  stage: deploy
  tags:
    - urf
    - linux
  script:
    - conan remote remove gitlab || true
    - conan remote add gitlab ${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/conan
    - conan create .
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload "urf_common_cpp*" --all --remote=gitlab -c
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/
