stages:
  - prepare
  - build

install:
  stage: prepare
  tags:
    - urf
    - linux
  script:
    - conan install . -if build/conan

build:
  stage: build  
  tags:
    - urf
    - linux
  script:
    - conan build . -if build/conan
    
